### PR TITLE
Add contributing documentation

### PR DESCRIPTION
**Pull request by idelvall**
Updates documentation, and runs tests in a satellite.
Also added CLA verification

### CODE REVIEW

**Review by idodod — APPROVED** [review]
thanks for doing this!

**Review by alexcb — COMMENTED** [review]
Can comment on why the license is changing.

**Comment by idelvall** [comment]
> Can comment on why the license is changing.

Just changed it to use the same as Earthly core. Why using different ones otherwise?

**Comment by vladaionescu** [comment]
MPL is simply a very popular non-copy-left license. That's the reason we chose it for Earthly, and it makes sense to remain consistent and choose it here too.

**Pull request merged**
